FROM microsoft/aspnetcore-build:2.0
COPY . ./app
WORKDIR /app

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]

RUN dotnet publish -c Debug -o build

FROM microsoft/aspnetcore:2.0

WORKDIR /app

COPY ./src/API/build .
EXPOSE 80

ENTRYPOINT ["dotnet", "PetProjects.MtsManagementApi.API.dll"]